### ISSUE TITLE
varnames

### ISSUE THREAD

**Issue by stared** [markdregan/Hangout-with-PYMC3#9]
For the current `pymc3` in `pm.traceplot` it should be `varnames=`, not `vars=`.

**Comment by markdregan** [comment]
Good catch @stared - syntax must have changed in recent release. Would you be able to submit a PR?

**Comment by stared** [comment]
It's what I thought. I would be happy to do PR.!

Since I am learning PyMC3 (rather than running your notebooks), I would test also for other stuff. E.g. 

```
messages = pd.DataFrame(fetch_messages(json_data), columns=cols).sort(['conversation_id', 'timestamp'])
```

gives `FileNotFoundError: [Errno 2] No such file or directory: 'data/hangouts.json'`. Did you miss to upload this file?

**Comment by markdregan** [comment]
Ah yes. the 'hangouts.json' file is not uploaded because it contains sensitive content. So the first notebook must be updated by me. There should be a csv file to use for the remaining notebooks.

**Comment by stared** [comment]
Yeah, I should read things before I run them. PR is coming in short time. In any case - some models are sluggishly slow on my Mac Book Pro 2009.

**Comment by stared** [comment]
PR is here: https://github.com/markdregan/Bayesian-Modelling-in-Python/pull/10
